### ISSUE TITLE
Hi, the paper is ready?

### ISSUE THREAD

**Issue by raphacosta27** [bluemoon93/GeoFriends2#1]

**Comment by david-simoes-93** [comment]
Yes, you can find it [here](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8489372). This [update](https://github.com/bluemoon93/GeoFriends2-v2) may also be useful to you. Thank you for bringing this up, I've updated the README.

**Comment by raphacosta27** [comment]
Thank you for answering! 
I’m planning to do a project that is similar, involving OpenAi and GeoFriends2 and it will be nice for having your job as a bibliography!
